### ISSUE TITLE
About SRM data processing

### ISSUE THREAD

**Issue by JaesikKim** [stasaki/clei2block#1]
Hello. I have one question about ROSMAP SRM data processing.
I was trying to find the details about that in the paper, but I couldn't find.
If I'm wrong, please correct me.

In the [ROSMAP LC-SRM link](https://www.synapse.org/#!Synapse:syn21448467), there are two rounds for measurements, and each of them has features for multiple peptides
- Round 1 : 67 peptides
- Round 2 : 119 peptides
(# of proteins should be lower than # of peptides, because multiple peptides from single protein were measured)

So, my question is how did you get the final 121 proteins?, and how did you make the representative value for each protein (from multiple peptides)?

Thanks!

Jaesik

**Comment by stasaki** [comment]
Hi Jaesik,

I removed peptides with post-translational modifications and ones without mRNA levels. I ran an association test for each peptide independently and used the best estimate for each protein for each dataset.

Best,
Shinya

**Comment by JaesikKim** [comment]
Thanks for fast and kind response! 
It is really helpful.

Best,
Jaesik
